### ISSUE TITLE
Version 1 Bot Didn't Respond Back

### ISSUE THREAD

**Issue by bajoelkid12** [Eloise1988/OPENAI#7]
Hi @Eloise1988 ,

I'm trying your version 1 code.

The code run well, but my bot didn't respond back.

I run it via python 3.9 in Spyder.

The print(data) seems working, but somehow the bot didn't respond.
`url = f'https://api.telegram.org/bot{BOT_TOKEN}/getUpdates?offset={last_update}'
    response = requests.get(url, timeout=5)
    data = json.loads(response.content)
    print(data) `

<img width="379" alt="image" src="https://user-images.githubusercontent.com/80200305/221417534-7f57d8b9-7811-43ff-83b2-82a050035cb5.png">

**Comment by Eloise1988** [comment]
Version 1 Debug:
1. Continus printing of file exists is NORMAL, I will change the code so that it doesn't write it anymore. Seems to be confusing.
2. 'Message' is an error suggesting your bot hasn’t been well configured. make sure your bot works before you run the code, read [Medium](https://eloise88.medium.com/create-your-own-hilarious-chatgpt-bot-in-telegram-with-python-a-step-by-step-guide-466e8a510c0d) on the telegram bot
3. Make sure that chatbot.txt exist and has the right path, put 1 on the first line if file is empty
3. Check that your BOT has ADMIN access to your group
4. Make sure in the code, that you replaced ask_chatgptbot  with your BOT NAME
5. Check on https://api.telegram.org/bot{ACCESS TOKEN}/getUpdates that you see all messages sent to your bot and that you are not getting 404 errors. If you do have errors, check with telegram or recreate a new bot.
V1 medium:

https://eloise88.medium.com/create-your-own-hilarious-chatgpt-bot-in-telegram-with-python-a-step-by-step-guide-466e8a510c0d

**Comment by KaladinDMP** [comment]
Im having the same issue. Responds to /img but not to mentions. I tried the debug for version 1 and also read the step by step guide. Cant figure out what im doing wrong if anything but its driving me nuts.

**Comment by Eloise1988** [comment]
> Im having the same issue. Responds to /img but not to mentions. I tried the debug for version 1 and also read the step by step guide. Cant figure out what im doing wrong if anything but its driving me nuts.

Could you please provide more information? Are you receiving any error messages or are you able to see the questions you asked the bot on your console? I require additional details to determine a solution.

**Comment by KaladinDMP** [comment]
I'm sorry I forgot I ended up posting this here or I would have answered back. For me the issue seems to be I was trying to use the text-ada-001 version..
 That one didn't respond to mentions just /img. No errors I could even see my posts as mentions not bot etc just no response. I ended up using the default for version one which is gpt-3-whatever instead of text-codename-00X. This solved my problem. I apologize for not editing my post. Thanks for sharing this. 

Been great fun so far the only issue I have is after some time the py seems to close and has to restarted. I'm running it through my whatbox server through screen on ssh so the expected results is it shouldn't close until I tell it to. My other telegram bot will stay up for weeks or months as long as it doesn't crash or my server doesn't restart. Not a big deal though but figured I'd mention. Thanks again

**Comment by Eloise1988** [comment]
> I'm sorry I forgot I ended up posting this here or I would have answered back. For me the issue seems to be I was trying to use the text-ada-001 version.. That one didn't respond to mentions just /img. No errors I could even see my posts as mentions not bot etc just no response. I ended up using the default for version one which is gpt-3-whatever instead of text-codename-00X. This solved my problem. I apologize for not editing my post. Thanks for sharing this.
> 
> Been great fun so far the only issue I have is after some time the py seems to close and has to restarted. I'm running it through my whatbox server through screen on ssh so the expected results is it shouldn't close until I tell it to. My other telegram bot will stay up for weeks or months as long as it doesn't crash or my server doesn't restart. Not a big deal though but figured I'd mention. Thanks again

I'm glad it works and thanks for the useful feedback!
